### ISSUE TITLE
How to check AutoStart option is on or off ??? 

### ISSUE THREAD

**Issue by vishalvasoya** [judemanutd/AutoStarter#1]
your solution has completed and its works properly , 
but how to know AutoStart permission is on or off in android device.
How to check AutoStart option is already on for my App in Xiaomi (oppo / vivo) phone Security App programmatically in android ,

**Comment by judemanutd** [comment]
In short you can't. The only way is to redirect the user to the screen, android gives you no control over what happens on that screen, at best you could keep a flag so whenever that screen is opened you could alternate the flag.

**Comment by vishalvasoya** [comment]
Thanks very much for your response.... 😊
