### ISSUE TITLE
New logo/Icon

### ISSUE THREAD

**Issue by mansya** [judemanutd/AutoStarter#2]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by judemanutd** [comment]
@mansya sounds like a nice idea, did you've something in mind, I don't mind giving you credits for the design in the description

**Comment by judemanutd** [comment]
I like the colored one with just the logo, why don't you go ahead and make a pull request.

**Comment by mansya** [comment]
I have upload all files to this link.
https://drive.google.com/open?id=1Vi8XNJgPjE0mWC5dCZxvQuhgvUAqmBpO

and i have to sent you Pull Request. please check

**Comment by judemanutd** [comment]
@mansya thanks
