### ISSUE TITLE
Is it possible to enable autostart on Techno phones

### ISSUE THREAD

**Issue by enriquejuan2** [judemanutd/AutoStarter#22]
All techno phones have issues with autostart, is it possible to enable autostart on them?

**Comment by judemanutd** [comment]
Hey @enriquejuan2 I'm based in India and I don't think techno sells over here and without the actual device its pretty much impossible to get the package name that relates to the auto start screen. 

If you do have access to the phone, just plug it in and take a look at logcat for the packages that are called, you only need the package name ( could look something like this `com.xxx.securitycenter` ) and the activity name of the autostart screen ( could look something like this `com.xxx.autostart.AutoStartManagementActivity` ).Each OEM has its own version so there is no standard api for this. Once you have those, create a new intent like below and start it, if you've got the correct ones you'll see the auto start screen start up. 

```kotlin
val intent = Intent()
intent.component = ComponentName(packageName, componentName)
context.startActivity(intent)
```

P.S. If it does work, do add it to the library so others can have it as well.

**Comment by enriquejuan2** [comment]
Hi @judemanutd Thanks for the quick reply. I have the actual device let me try to get to the autostart screen and get the activity name and package name.

**Comment by judemanutd** [comment]
Awesome, It's going to be quite a bit of trial and error but I think you can look out for words like autostart, powersaver, optimize, startup,
