### ISSUE TITLE
Huawei and Samsung support

### ISSUE THREAD

**Issue by NoHarmDan** [judemanutd/AutoStarter#25]
Hi, first of all, you got a great library, very lightweight and easy to use!

Since the readme mentions **Huawei** devices not being tested, I took the liberty of doing so on two devices I have available. 

- P9 lite mini (**SLA-L22**) running **Android 7.0 and EMUI 5.1.3**. This one **works perfectly** with the intent present in the library. 

- Y6 2019 (**MRD-LX1**) running **Android 9 and EMUI 9.1.0**. This one doesn't work at all - simple `ActivityNotFoundException` since the System Manager has apparently changed. So I did some reverse engineering to see what's what.

Turns out there's a screen that might be of interest to you and **can** be opened with an intent (found a whole bunch of interesting activities, but they usually require a Huawei's custom permission). 
It's the "**App launch**" screen that can be found in the device settings under the "Battery" screen. To open it, you can use 
```
ComponentName("com.huawei.systemmanager",                     
    "com.huawei.systemmanager.startupmgr.ui.StartupNormalAppListActivity")
```
Now I don't know which versions of EMUI have what, but I'd wager, based on what [backgroundable](https://github.com/dirkam/backgroundable-android) says, that anything newer than EMUI 5 (which probably includes Android Oreo and up) isn't gonna support `com.huawei.systemmanager.optimize.process.ProtectActivity`. 

Getting back to [backgroundable](https://github.com/dirkam/backgroundable-android) and **Samsung**, I recommend checking out what they suggest, which is using 
```
ComponentName("com.samsung.android.lool",
    "com.samsung.android.sm.ui.battery.BatteryActivity")
```
Two things to consider here though: this only works on **Android 7.0 and up** and it's not really about autostart - it's a "power monitor" setting, which I suppose lets you decide whether you want Samsung's power management (not to mistake with Android OS default power management) to screw your app up or not. This may or may not include autostart features.

Personally, I do recommend including Samsung in supported manufacturers, since their phones really do suck when it comes to running apps that have scheduled and/or background tasks.

**Comment by judemanutd** [comment]
@NoHarmDan dude!! **thank you** :100: 

Thanks for testing those out, I'll definitely update the readme and add those to the library. At this point its pretty much a combination of various activity names and brute force to get it working since the package names keep changing but thanks again for taking the time to do this. 

I'm a little busy but I'll get to this over the weekend and have these changes merged into the main branch.
