### ISSUE TITLE
Wrong activity on older Asus devices

### ISSUE THREAD

**Issue by NoHarmDan** [judemanutd/AutoStarter#28]
It's me again!

The activity `com.asus.mobilemanager.powersaver.PowerSaverSettings` doesn't exist on Asus with Android 5. However, through my immeasurable skills of reverse engineering, I have found the right one that does exist:
```kotlin
ComponentName("com.asus.mobilemanager",
        "com.asus.mobilemanager.autostart.AutoStartActivity")
```

Don't know which version of Android has which, so I guess just consider adding a fallback to this activity if the current one is not found.

**Comment by judemanutd** [comment]
immeasurable skills indeed :100: @NoHarmDan keep em coming, this will be super useful to everyone using this library. I saw the other issue as well that you created, thanks for that. I'm a little busy during the week but will take a look at both of those issues and make the necesarry changes.
