### ISSUE TITLE
simple code for check intent is exist 

### ISSUE THREAD

**Issue by captain-miao** [judemanutd/AutoStarter#29]
```
        Intent intent = new Intent();
        intent.setComponent(new ComponentName(packageName, componentName));
        if (intent.resolveActivity(context.getPackageManager()) != null) {
            // the intent is exist
        }
```

**Comment by judemanutd** [comment]
thanks @captain-miao , I've added this to the existing roadmap and should be integrated once the [v2](https://github.com/judemanutd/AutoStarter/milestone/1) is complete

**Comment by judemanutd** [comment]
Added support for this in https://github.com/judemanutd/AutoStarter/pull/69
