### ISSUE TITLE
Not Working in Samsung Galaxy M20

### ISSUE THREAD

**Issue by radheyshyamjat** [judemanutd/AutoStarter#33]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.samsung.android.lool/com.samsung.android.sm.ui.battery.BatteryActivity}; have you declared this activity in your AndroidManifest.xml?
System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2069)
W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1717)
W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:5250)
W/System.err:     at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
  at android.app.Activity.startActivityForResult(Activity.java:5208)
2020-01-19 20:24:09.357 29121-29121/wocs.solutions.tracker W/System.err:     at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
W/System.err:     at android.app.Activity.startActivity(Activity.java:5579)
 W/System.err:     at android.app.Activity.startActivity(Activity.java:5547)
 W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:300)
 W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartSamsung(AutoStartPermissionHelper.kt:283)
 W/System.err:     at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:108)
 W/System.err:     at Activity.NewDashboardActivity.onCreate(NewDashboardActivity.kt:85)
W/System.err:     at android.app.Activity.performCreate(Activity.java:7955)
W/System.err:     at android.app.Activity.performCreate(Activity.java:7944)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loop(Looper.java:237)
android.app.ActivityThread.main(ActivityThread.java:7807)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by chrisonline** [comment]
@judemanutd I get the same on a Samsung Galaxy S8. So I have checked how the activity name is.
Instead of com.samsung.android.sm.ui.battery.BatteryActivity
It is com.samsung.android.sm.battery.ui.BatteryActivity!

So either they have changed this or it was always false ;-)

**Comment by judemanutd** [comment]
This should be resolved by https://github.com/judemanutd/AutoStarter/pull/69 but feel free to open this issue back up in case it does not
