### ISSUE TITLE
Opens Settings screen again if Autorun permission is already enabled.

### ISSUE THREAD

**Issue by zoptaltechnical** [judemanutd/AutoStarter#4]
It opens Settings screen again if autorun permission is already enabled by user

**Comment by judemanutd** [comment]
Hey, given that this is more on an OEM specific feature, there isn't any api that can be used to check if the user has checked autorun or not, I would suggest maintaining a local flag to see if the user visited the screen but there are also chances where the user visited the screen but never checked the autorun button.

**Comment by zoptaltechnical** [comment]
"I would suggest maintaining a local flag to see if the user visited the screen but there are also chances where the user visited the screen but never checked the autorun button." - This is main problem you know for creating this issue , I guess this cannot be handled .
