### ISSUE TITLE
Note working on Xiaomi Redmi Note 7

### ISSUE THREAD

**Issue by linuxgg** [judemanutd/AutoStarter#41]
`AutoStartPermissionHelper.getInstance().isAutoStartPermissionAvailable(getApplicationContext())`

gives `true` as init installed(no any special action, just click apk and install). 
And there's no action after call `  AutoStartPermissionHelper.getInstance().getAutoStartPermission(getApplicationContext());`

**Comment by omranjamal** [comment]
+1

**Comment by judemanutd** [comment]
This should be resolved by https://github.com/judemanutd/AutoStarter/pull/69 but feel free to open this issue back up in case it does not
