### ISSUE TITLE
AndroidRuntimeException: Calling startActivity()

### ISSUE THREAD

**Issue by praveenbbhati** [judemanutd/AutoStarter#42]
Hi,

I'm using this library via a [flutter plugin.](https://pub.dev/packages/autostart) 

Device: OnePlus 7 GM1901
OS: Oxygen OS 10.3.2GM57AA

it returns true for isAutoStartPermissionAvailable

any help is appreciated. 

Logs :
`W/System.err(28183): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
W/System.err(28183): 	at android.app.ContextImpl.startActivity(ContextImpl.java:964)
W/System.err(28183): 	at android.app.ContextImpl.startActivity(ContextImpl.java:940)
W/System.err(28183): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
W/System.err(28183): 	at com.judemanutd.autostarter.AutoStartPermissionHelper.startIntent(AutoStartPermissionHelper.kt:325)
W/System.err(28183): 	at com.judemanutd.autostarter.AutoStartPermissionHelper.autoStartOnePlus(AutoStartPermissionHelper.kt:308)
W/System.err(28183): 	at com.judemanutd.autostarter.AutoStartPermissionHelper.getAutoStartPermission(AutoStartPermissionHelper.kt:118)
W/System.err(28183): 	at com.yin.autostart.AutostartPlugin.onMethodCall(AutostartPlugin.java:53)`

**Comment by minuhariharan** [comment]
I am also facing the same issue and unable to use this plugin, what is the fix for this? I am getting this issue for getAutoStartPermission() for One Plus, Redmi

**Comment by judemanutd** [comment]
@minuhariharan could you take a look at the steps mentioned in https://github.com/judemanutd/AutoStarter/issues/47#issuecomment-651002811 and post the results here once you have them, this should allow for better debugging.

**Comment by agent10** [comment]
The same thing. I'm calling getAutoStartPermission() from foreground service and it cannot be done without FLAG_ACTIVITY_NEW_TASK for intent

**Comment by judemanutd** [comment]
@agent10 I think #62 might resolve your issue here, I'm waiting on a slight modification to the PR after which I can accept the change

**Comment by judemanutd** [comment]
This should be resolved by https://github.com/judemanutd/AutoStarter/pull/69
