### ISSUE TITLE
Add Tecno mobile and Infinix to the supported devices

### ISSUE THREAD

**Issue by varungupta85** [judemanutd/AutoStarter#44]
We get a good amount of tickets from the following two manufacturers that seem to have the auto-start setting:

Tecno Mobile - https://www.tecno-mobile.in/home/
Infinix - https://www.infinixmobiles.in/

I don't have these two phones in my test inventory. So, I can't figure out the instructions myself but it will be great help to support these manufacturers.

**Comment by judemanutd** [comment]
Closing this issue, please follow #47 since the user that reported the issue does have access to the two phones.
