### ISSUE TITLE
[OnePlus 7 Pro] getAutoStartPermission exception

### ISSUE THREAD

**Issue by JeanChristophePal** [judemanutd/AutoStarter#45]
`W/System.err: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.oneplus.security/com.oneplus.security.chainlaunch.view.ChainLaunchAppListActivity}; `

**Comment by judemanutd** [comment]
@JeanChristophePal  I would urge you to follow the same steps mentioned in https://github.com/judemanutd/AutoStarter/issues/47#issuecomment-651002811 and post the result here in order to get the latest intent.

**Comment by j4zib** [comment]
> @JeanChristophePal I would urge you to follow the same steps mentioned in [#47 (comment)](https://github.com/judemanutd/AutoStarter/issues/47#issuecomment-651002811) and post the result here in order to get the latest intent.

[activities.txt](https://github.com/judemanutd/AutoStarter/files/5149076/activities.txt)

**Comment by divyeshsachan** [comment]
I confirm this issue on OnePlus 6T.
I also spent hours finding activity associated with battery optimization, but failed.
Log generated using "adb shell dumpsys activity" didn't helped.

**Comment by KieronQuinn** [comment]
```
val batteryIntent = Intent("android.settings.APP_BATTERY_SETTINGS").apply {
    data = Uri.parse("package:${BuildConfig.APPLICATION_ID}")
}
```

Will get an intent for the OnePlus Battery Optimisation settings with the app selected on newer devices.

**Comment by judemanutd** [comment]
This should be resolved by https://github.com/judemanutd/AutoStarter/pull/69 but feel free to open this issue back up in case it does not
