### ISSUE TITLE
OnePlus

### ISSUE THREAD

**Issue by jschhabra** [judemanutd/AutoStarter#5]
I am facing similar issue on OnePlus. Do you know how to support OnePlus device running on android 8.1

**Comment by judemanutd** [comment]
Hey @jschhabra, unfortunately  I do not have access to a OnePlus device so I have not got a chance to figure out its mechanisms yet, you can follow this thread where a developer has a similar issue with a OnePlus device, you might find an answer there.

[https://github.com/invertase/react-native-firebase/issues/1238#event-1771122177](url)

**Comment by jschhabra** [comment]
Thanks,
It helped!
