### ISSUE TITLE
Realme 3 auto statup intent.

### ISSUE THREAD

**Issue by Partha-Sarker** [judemanutd/AutoStarter#53]
I've realme 3 and it is not supported. I want to know how can I figure out the intent name for startup manager? I can open the startup manager from settings but don't know the name to open it programmatically.

**Comment by Prometheus3k** [comment]
Manually open the StartupManager so it's displayed on your devices screen.
then in terminal run this
 adb shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp|mObscuringWindow'

You should get some output like below:

> mFocusedApp=AppWindowToken{
>  e224f9d token=Token{
>    d8b2e74 ActivityRecord{
>      1d97647 u0 com.google.android.dialer/com.google.android.dialer.extensions.GoogleDialtactsActivity t1078
>    }
>  }
> }

The bit in the middle tells you how you create an intent to possibly launch it.
e.g.
```
val packageName = "com.google.android.dialer"
val className = "com.google.android.dialer.extensions.GoogleDialtactsActivity"
val cn = ComponentName(packageName, className)
val intent = Intent()
intent.component = cn
ctx.startActivity(intent)
```

Please note though, some devices are now blocking the launch of StartupManager (need to be signed with OEM permissions see  #51 for Oppo example)

**Comment by Partha-Sarker** [comment]
> Manually open the StartupManager so it's displayed on your devices screen.
> then in terminal run this
> ` adb shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp|mObscuringWindow'`
> 
> You should get some output like below:
> 
> > mFocusedApp=AppWindowToken{
> > e224f9d token=Token{
> > d8b2e74 ActivityRecord{
> > 1d97647 u0 com.google.android.dialer/com.google.android.dialer.extensions.GoogleDialtactsActivity t1078
> > }
> > }
> > }
> 
> The bit in the middle tells you how you create an intent to possibly launch it.
> e.g.
> 
> ```
> val packageName = "com.google.android.dialer"
> val className = "com.google.android.dialer.extensions.GoogleDialtactsActivity"
> val cn = ComponentName(packageName, className)
> val intent = Intent()
> intent.component = cn
> ctx.startActivity(intent)
> ```
> 
> Please note though, some devices are now blocking the launch of StartupManager (need to be signed with OEM permissions see #51 for Oppo example)

Thanks,  will check this out.
