### ISSUE TITLE
how can implement?

### ISSUE THREAD

**Issue by Qurexhi** [judemanutd/AutoStarter#55]
brother how can implement autostarter in other project?
means how call autostarter in main activity

**Comment by nicemak** [comment]
`val autoStartAvailable = AutoStartPermissionHelper.getInstance().isAutoStartPermissionAvailable(this)
val success = AutoStartPermissionHelper.getInstance().getAutoStartPermission(this@MainActivity)
var message = "Failed"
if (success) message = "Successful"

Toast.makeText(this@MainActivity, "Supports AutoStart: $autoStartAvailable, Action $message", Toast.LENGTH_SHORT).show()`

**Comment by judemanutd** [comment]
Hey @Qurexhi I don't think I get your question, could you elaborate a little more of what exactly you're trying to do and how its different from the sample provided already.
