### ISSUE TITLE
How to check if autostart permission is enabled or not?

### ISSUE THREAD

**Issue by amitdoiphode11** [judemanutd/AutoStarter#6]
"I would suggest maintaining a local flag to see if the user visited the screen but there are also chances where the user visited the screen but never checked the autorun button." - This is main problem you know for creating this issue , I guess this cannot be handled .

_Originally posted by @zoptaltechnical in https://github.com/judemanutd/AutoStarter/issues/4#issuecomment-406562267_

**Comment by judemanutd** [comment]
I am open to pull requests but I do not currently see any open api in android that could be used to achieve this.
