### ISSUE TITLE
check if autostart permission is active for my app

### ISSUE THREAD

**Issue by Kassan424kh** [judemanutd/AutoStarter#61]
Every time i open the app, it would open autostart settings window, how can I check if the `autostart` permission is selected before open the `settings` window?
do you have any idea?

```
class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        if (AutoStartPermissionHelper.getInstance().isAutoStartPermissionAvailable(context))
            AutoStartPermissionHelper.getInstance().getAutoStartPermission(context)
    }
}
```

**Comment by judemanutd** [comment]
Closing since this is a duplicate of #4 , given that these aren't standard android apis, there is no way of knowing this information.
