### ISSUE TITLE
Android 11 policies

### ISSUE THREAD

**Issue by GuillaumeBourge** [judemanutd/AutoStarter#65]
Hi, thanks for this lib! :)
You did not mention about restrictions coming with Android 11 :
https://proandroiddev.com/how-to-get-users-installed-apps-in-android-11-b4a4d2754286

Maybe you can add in the manifest of the lib or add in the documentation ?

**Comment by judemanutd** [comment]
Hey @GuillaumeBourge thanks so much for pointing this one out, it's been awhile since I have kept myself up to date with the changes in the android system but I will definitely take a look at this. Thank you

**Comment by judemanutd** [comment]
This should be resolved by https://github.com/judemanutd/AutoStarter/pull/69 but feel free to open this issue back up in case it does not
