### ISSUE TITLE
toLowerCase fail

### ISSUE THREAD

**Issue by naimyag** [judemanutd/AutoStarter#66]
AutoStartPermissionHelper.kt
 ->getAutoStartPermission()
   
Build.BRAND.toLowerCase(Locale.getDefault())

When the phone locale is Turkish, the lowercase letter of "HUAWEI" returns "huaweı" and does not match.  So big "I" turns into Turkish little "ı", "i" doesn't.

https://stackoverflow.com/questions/11063102/using-locales-with-javas-tolowercase-and-touppercase

**Comment by judemanutd** [comment]
This should be resolved by https://github.com/judemanutd/AutoStarter/pull/69
