### ISSUE TITLE
can't build project after adding this dependencies please help me

### ISSUE THREAD

**Issue by eranilsharma** [judemanutd/AutoStarter#7]
Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest
> Task :app:processDebugResources
> Task :app:compileDebugKotlin
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources
> Task :app:javaPreCompileDebug

> Task :app:compileDebugJavaWithJavac
Gradle may disable incremental compilation as the following annotation processors are not incremental: butterknife-compiler-8.2.1.jar (com.jakewharton:butterknife-compiler:8.2.1), auto-service-1.0-rc2.jar (com.google.auto.service:auto-service:1.0-rc2).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:packageInstantRunResourcesDebug
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :app:processInstantRunDebugResourcesApk
> Task :app:fastDeployDebugExtractor UP-TO-DATE
> Task :app:generateDebugInstantRunAppInfo
> Task :app:checkManifestChangesDebug
> Task :app:transformClassesWithExtractJarsForDebug UP-TO-DATE
> Task :app:transformClassesWithInstantRunVerifierForDebug
> Task :app:transformClassesWithDependencyCheckerForDebug
> Task :app:compileDebugNdk NO-SOURCE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForDebug
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug
> Task :app:transformNativeLibsAndResourcesWithJavaResourcesVerifierForDebug
> Task :app:transformClassesWithInstantRunForDebug
> Task :app:transformClassesAndClassesEnhancedWithInstantReloadDexForDebug
> Task :app:incrementalDebugTasks
> Task :app:preColdswapDebug
> Task :app:transformClassesWithDexBuilderForDebug

> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
AGPBI: {"kind":"error","text":"Program type already present: android.support.design.widget.CoordinatorLayout$Behavior","sources":[{}],"tool":"D8"}

> Task :app:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.design.widget.CoordinatorLayout$Behavior

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 5s
39 actionable tasks: 23 executed, 16 up-to-date

**Comment by judemanutd** [comment]
From the looks of it, it seems that you have crossed the 65k method limit, you might have to enable multidex. 

Could you post your project and app `build.gradle` files

**Comment by judemanutd** [comment]
I haven't got the opportunity to work with those phones so unfortunately I can't help you with those yet, have you tried going to the autostart manager or battery optimizations manager ( the settings are usually under similar names ) and adding your app to it and checking if it atleast works then?

**Comment by eranilsharma** [comment]
can i get any helping link or example
